version: "2"
services:
  elasticsearch:
    image: elasticsearch:7.2.0
    restart: always
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - /h/elasticsearch-data/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  kibana:
    image: kibana:7.2.0
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    external_links:
      - elasticsearch
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      - /h/kibana-data/:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - elk

networks:
  elk:
    driver: bridge
