version: "2"
services:
  prometheus-server:
    image: prom/prometheus
    restart: always
    ports:
      - 9001:9090
    volumes:
      - ./config:/etc/prometheus
    networks:
      - monitor
    external_links:
      - prometheus-alertmanager:alertmanager 

  prometheus-alertmanager:
    image: prom/alertmanager
    restart: always
    volumes:
      - ./alarm:/etc/alertmanager
    ports:
      - 9002:9093
    networks:
      - monitor

  prometheus-node:
    image: prom/node-exporter
    restart: always
    ports:
      - 9102:9100
    networks:
      - monitor

networks:
  monitor:
    driver: bridge