version: "2"
services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - "/data/data/mysql:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"
    ports:
      - 9306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"

