version: "2"
services:
  redis-sentinel-0:
    image: redis
    container_name: redis-sentinel-0
    restart: always
    command: redis-sentinel /usr/local/etc/redis/redis-sentinel-0.conf
    ports:
      - 26380:26379
    volumes:
      - ./conf/sentinel:/usr/local/etc/redis
    networks:
      - redis_net
  redis-sentinel-1:
    image: redis
    container_name: redis-sentinel-1
    restart: always
    command: redis-sentinel /usr/local/etc/redis/redis-sentinel-1.conf
    ports:
      - 26381:26379
    volumes:
      - ./conf/sentinel:/usr/local/etc/redis
    networks:
      - redis_net
  redis-sentinel-2:
    image: redis
    container_name: redis-sentinel-2
    restart: always
    command: redis-sentinel /usr/local/etc/redis/redis-sentinel-2.conf
    ports:
      - 26382:26379
    volumes:
      - ./conf/sentinel:/usr/local/etc/redis
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
